/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f8faf6",
        "surface-dim": "#d8dbd7",
        "surface-bright": "#f8faf6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f1",
        "surface-container": "#eceeeb",
        "surface-container-high": "#e7e9e5",
        "surface-container-highest": "#e1e3e0",
        "on-surface": "#191c1b",
        "on-surface-variant": "#404944",
        "inverse-surface": "#2e312f",
        "inverse-on-surface": "#eff1ee",
        "outline": "#707974",
        "outline-variant": "#bfc9c3",
        "surface-tint": "#2b6954",
        "primary": "#003527",
        "on-primary": "#ffffff",
        "primary-container": "#064e3b",
        "on-primary-container": "#80bea6",
        "inverse-primary": "#95d3ba",
        "secondary": "#006780",
        "on-secondary": "#ffffff",
        "secondary-container": "#76dcff",
        "on-secondary-container": "#006077",
        "tertiary": "#4f1f19",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6b342d",
        "on-tertiary-container": "#ea9e93",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#b0f0d6",
        "primary-fixed-dim": "#95d3ba",
        "on-primary-fixed": "#002117",
        "on-primary-fixed-variant": "#0b513d",
        "secondary-fixed": "#b7eaff",
        "secondary-fixed-dim": "#6cd3f7",
        "on-secondary-fixed": "#001f28",
        "on-secondary-fixed-variant": "#004e61",
        "tertiary-fixed": "#ffdad5",
        "tertiary-fixed-dim": "#ffb4a9",
        "on-tertiary-fixed": "#380d08",
        "on-tertiary-fixed-variant": "#6e372f",
        "background": "#f8faf6",
        "on-background": "#191c1b",
        "surface-variant": "#e1e3e0"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      }
    },
  },
  plugins: [],
};
